import os
import glob
import pickle
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.cuda.amp import autocast, GradScaler

from src.agent.model import HexAlphaNet

class HexDataset(Dataset):
    """Custom Dataset to load self-play experience batches."""
    def __init__(self, data_dir="training/data"):
        self.states = []
        self.policies = []
        self.rewards = []
        
        # Find all pickle files generated by self_play.py
        file_paths = glob.glob(os.path.join(data_dir, "*.pkl"))
        for path in file_paths:
            with open(path, "rb") as f:
                data = pickle.load(f)
                self.states.append(data["states"])
                self.policies.append(data["policies"])
                self.rewards.append(data["rewards"])
                
        if not self.states:
            raise ValueError(f"No training data found in {data_dir}. Run self_play.py first!")
            
        # Concatenate all loaded batches into massive single arrays
        self.states = np.concatenate(self.states, axis=0)
        self.policies = np.concatenate(self.policies, axis=0)
        self.rewards = np.concatenate(self.rewards, axis=0)
        
    def __len__(self):
        return len(self.states)
        
    def __getitem__(self, idx):
        return (
            torch.tensor(self.states[idx], dtype=torch.float32),
            torch.tensor(self.policies[idx], dtype=torch.float32),
            torch.tensor(self.rewards[idx], dtype=torch.float32)
        )

def train(model_save_path="models/checkpoints/best_model.pth", epochs=5, batch_size=128):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on device: {device}")
    
    # 1. Prepare Data
    dataset = HexDataset()
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True)
    
    # 2. Initialize Model, Optimizer, and Scaler (for RTX 4070 fp16 optimization)
    model = HexAlphaNet(board_size=11).to(device)
    if os.path.exists(model_save_path):
        model.load_state_dict(torch.load(model_save_path, map_location=device))
        print("Loaded previous checkpoint.")
        
    optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4) # weight_decay is the L2 term
    scaler = GradScaler()
    
    # 3. Training Loop
    model.train()
    for epoch in range(epochs):
        total_policy_loss = 0.0
        total_value_loss = 0.0
        
        for states, mcts_policies, rewards in dataloader:
            states, mcts_policies, rewards = states.to(device), mcts_policies.to(device), rewards.to(device)
            
            optimizer.zero_grad()
            
            # Use Automatic Mixed Precision for blazing fast forward passes
            with autocast():
                pred_policies_logits, pred_values = model(states)
                
                # Value Loss: Mean Squared Error
                value_loss = nn.functional.mse_loss(pred_values.squeeze(-1), rewards)
                
                # Policy Loss: Cross Entropy (using log_softmax on logits for numerical stability)
                pred_policies_log = nn.functional.log_softmax(pred_policies_logits, dim=1)
                policy_loss = -torch.sum(mcts_policies * pred_policies_log) / states.size(0)
                
                # Combined AlphaZero Loss
                loss = value_loss + policy_loss
                
            # Scaled Backpropagation
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            
            total_policy_loss += policy_loss.item()
            total_value_loss += value_loss.item()
            
        print(f"Epoch {epoch+1}/{epochs} | Policy Loss: {total_policy_loss/len(dataloader):.4f} | Value Loss: {total_value_loss/len(dataloader):.4f}")
        
    # 4. Save Checkpoint
    os.makedirs(os.path.dirname(model_save_path), exist_ok=True)
    torch.save(model.state_dict(), model_save_path)
    print(f"Model saved to {model_save_path}")

if __name__ == "__main__":
    train()